[project]
name = "backtrader-sample"
version = "0.1.0"
description = "backtrader performance test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backtrader>=1.9.76.123",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "pytz",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
